# Generated by Django 3.2.5 on 2022-11-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('course_num', models.IntegerField(null=True)),
                ('course_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('unique_name', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=10, null=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('course_choice', models.TextField(null=True)),
            ],
        ),
    ]
