# Generated by Django 3.2.5 on 2022-11-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='workload',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
